### ISSUE TITLE
What is needed to add subtitles

### ISSUE THREAD

**Issue by Forage** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#113]
Can you explain to me what is needed to add subtitles to a broadcast?
Only adding the following does not appear to be sufficient, even though I know the URL is correct:

`item.subtitles.append(subtitle_url)`

Based on the few channels that already have subtitles I can't seem to make out what else is needed to make it work.

**Comment by wwark** [comment]
Hi Forage,

What is the format of the subtitle you try to add and which channel ?

We add subtitles for FranceTV, 6Play and RTLPlay.be.

You have an example for 6play here https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/dev/resources/lib/channels/fr/6play.py (start line 451)

> subtitle_url = ''
        if plugin.setting.get_boolean('active_subtitle'):
            for asset in video_assets:
                if 'subtitle_vtt' in asset["type"]:
                    subtitle_url = asset['full_physical_path']

 > for asset in video_assets:
            if 'usp_dashcenc_h264' in asset["type"]:
                item = Listitem()
                item.path = asset['full_physical_path']
                if 'http' in subtitle_url:
                    item.subtitles.append(subtitle_url)
                item.label = item_dict['label']
                item.info.update(item_dict['info'])
                item.art.update(item_dict['art'])
                item.property['inputstreamaddon'] = 'inputstream.adaptive'
                item.property['inputstream.adaptive.manifest_type'] = 'mpd'
                item.property['inputstream.adaptive.license_type'] = 'com.widevine.alpha'
                item.property['inputstream.adaptive.license_key'] = URL_LICENCE_KEY % token
return item

To activate subtitle we add also a configuration in the plugin (set False by default) because the subtitle display directly and might be a problem for the persons don't need subtitle.

Thanks,
Wwark

**Comment by Forage** [comment]
I've seen all three examples, but I don't see anything more being done then `item.subtitles.append(subtitle_url)` to actualyl make it work.

Example: https://tt888.omroep.nl/tt888/AT_2106474

As you can see, plain and simple, calling a URL that gives you a format that is supposed to be supported, no?

**Comment by wwark** [comment]
It works on my side with you PR.
![screenshot from 2018-12-17 21-42-58](https://user-images.githubusercontent.com/469461/50114458-da98f600-0244-11e9-8f9a-0201678d1ad6.png)
![screenshot from 2018-12-17 21-42-29](https://user-images.githubusercontent.com/469461/50114460-da98f600-0244-11e9-9a43-5bb0636b5a98.png)

**Comment by wwark** [comment]
Do you enable this configuration in the plugin? "Enable Subtitle if present in the content"
![screenshot from 2018-12-17 21-48-17](https://user-images.githubusercontent.com/469461/50114705-7c204780-0245-11e9-8a99-97324cc6f2fb.png)

**Comment by Forage** [comment]
That is really weird... Yeah, I enabled that settings first. It is working for the French channels.
I tried it on my VM and physical TV, both do not show me any subtitles for BVN.tv.

Now I'm getting all 403's again, so I can't test any more. It's not the first time. It appears they have some protection we aren't properly handling yet. It'll work again tomorrow, so I'll come back to this matter then.

**Comment by wwark** [comment]
Ok don't hesitate to share logs in debug mode maybe we can find something.

**Comment by Forage** [comment]
Different tries, all to no avail.
While all settings are on default, it's basically a clean Kodi install with only this add-on added, I tried playing with the general subtitle settings. It does not explain why it works for the French channels, but it's still not working for BVN.tv.

You get the see the subtitle file in the video's subtitle settings, I see no such value.

The log does not even include an attempt to call the subtitle URL, but I see no other issues either:
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/2690508/kodi.log)

**Comment by Forage** [comment]
How likely is it that I'm either having some global subtitle setting different than you that makes it work for you or that I'm missing some dependency that you just happen to have through other means than required by this add-on?

I don't see how else two different installs on my side don't work and yours does.

**Comment by wwark** [comment]
Hi @Forage ,

I don't see anything in the logs can help to understand.

If it is ok for you I will merge your PR and test it on all my configurations (Android, Libreelec, windows and ubuntu for Kodi 17 and Kodi 18)
The test I have done is on Ubuntu Kodi 18 rc2 (ppa of Kodi).

We will see if it is related to one environnement.
Is it possible to make a screenshot below on your side when you play a BVN content to verify if the subtitle is present in the listitem or not. It can help us to see In what level the issue is.
![screenshot from 2018-12-17 21-42-29](https://user-images.githubusercontent.com/469461/50205528-d82fbc80-0368-11e9-983c-b3d172321276.png)

Regarding the 403, i think it is related to the cache. Because I tried in the logs you provided some bvn url and I get 403 (token without working anymore)
If it is the case we need to add the parameter maxage=-1 during the urlquick.get or post.

We will find the root cause :+1:

**Comment by Forage** [comment]
Concerning the merge of the pull request, go ahead. It should be all that's needed.
No need to add thanks to the change log every time though ;)

As I explained in my previous post, I have no such text in the dialog. Where you have the "POW_03738725" I have nothing. I do not know, however, when such a text should be appearing. Already when only providing the URL or when the URL is actually used.

Regarding the 403s: I'm already ahead of you ;) With some quick tests it looks like a random header will get rid of the 403s. Your `maxage=-1` might help for the problem that remains, not being able to start the same broadcast for a second time (no URL error). I was waiting for the problem to occur again to be able to confirm. I'll send a PR for that when all is fine.

**Comment by wwark** [comment]
ok I will do the merge this evening.

So it means the issue is during the construct of the item and not add the subtitle.

First test is to remove the "if" below or add some print before the if and after the if to verify the condiftion.
        if plugin.setting.get_boolean('active_subtitle'):
            item.subtitles.append(URL_SUBTITLE % video_id)

Other test Add directly the url of the subtitle to replace  "URL_SUBTITLE % video_id"

Maybe you already done this kind of tests.

**Comment by Forage** [comment]
I did indeed.

I didn't have the if clause at first. I added it just for the PR.
As a test I put the parsed URL in a variable before, and had it displayed in the UI as the plot to see if it was correct. The video details shows me the complete URL, the subtitle name in the subtitle dialog remains empty.

I'll just wait for the new beta to see if the update does the trick automagically. Even though I normally work in the Python files directly on the Kodi machine, maybe there's some weird caching going on.

**Comment by wwark** [comment]
Ok. I will inform you about my tests.
Is it possible on your side to test with Kodi 17.6 ?

**Comment by Forage** [comment]
I've downgraded Kodi 18 to 17.6 on my VM and this made the subtitles work(!)
Subsequently updating to 18 again keeps the subtitles displayed(!)

I'll check in a bit if clearing the add-on settings will do the trick on my other Kodi 18 installation.

**Comment by Forage** [comment]
Completely removing the add-on and it's dependencies (for as far as they were not used by other plugins), did not solve the problem oddly enough. I would hate having to recreate that install though.

I'll see if I can reinstall some other related plugins to try to see if that is going to do the trick. The most likely (CodeQuick and BeautifulSoup) did not make a difference.

**Comment by wwark** [comment]
Hi @Forage,

Maybe ask Kodi or Codequick can help this issue.

To know whom to ask, can you please try to use Kodi implementation to see if the issue remains.
Kodi => item.listitem.setSubtitles([subtitle_url])
Codequick => item.subtitles.append(subtitle_url)

I have also a question did you use the default skin of Kodi? What are the differences of your setup and the setup working in the test VM?

Thanks, 
Wwark

**Comment by Forage** [comment]
Subtitles have spontaneously started working for the remaining Kodi installation. I assume it was something not properly set during one of the intermediate Kodi deve updates that has been 'reset' now with one of the official installations of lately.
