### ISSUE TITLE
Downloading from the Official Repository will fail to write a path (even on Master User)

### ISSUE THREAD

**Issue by An-Untitled-Developer** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1174]
Device: Xbox One - Last Manufactured: 2020 [The last model]
------------
Issue: Failing to Write a Path.
------------
Found Manual Fix: No
------------
Other Manual Fixes: Beta Version from Zip DOES WORK but it'll says it doesn't support Widevine CDM. Catch-Up TV not affected. (If possible please support)
------------
Anything Else: No.

**Comment by darodi** [comment]
- Duplicate #1170

Xbox doesn't support Widevine CDM
see https://www.matthuisman.nz/2018/05/kodi-widevine-support.html


>Kodi 18 (and up) have implemented support for playback of Widevine DRM content via the [inputstream.adaptive](https://github.com/peak3d/inputstream.adaptive) add-on.
Note: Older versions of Kodi (17, 16 etc) do not support Widevine playback.

>Below is a list of supported platforms.
Platforms
>UWP (Windows Store / Xbox) - NO
>- These platforms do not support Widevine playback

https://forum.kodi.tv/showthread.php?tid=349961&pid=2907271#pid2907271
>Inputstream is a binary add-on.
UWP runs in a sandbox & won't run external dll's for security purposes.
So the add-on needs to be included with the build for it to work.

>This is also the main reason Widevine DRM won't playback.
That needs to use a widevinecdm.dll which can't be included in kodi due to licensing. 

@An-Untitled-Developer 
your issue is unrelated to CUTVM. 


@joaopa00 
I think this issue could be closed.
