### ISSUE TITLE
IPTV simple : connection lost

### ISSUE THREAD

**Issue by Jaunattend** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1179]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:

Hello, 
After a fresh install of catchup on Shield TV pro from repository, unable to have TV integration. 

Thank you for any help.

### To Reproduce
Steps to reproduce the behaviour:
1. Open kodi
2. Pop UP : IPTV simple connection lost
3. No Channel or TV guide 

### Expected behaviour
A clear and concise description of what you expected to happen:

Channel and guide in live tv

### Actual behaviour
Tell us what happens instead:

Nothing appear

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [x ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 20.2
 - Catch-up TV & More version: 0.2.39-beta28
 - Installation method: from repository

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by calvin4242** [comment]
Connection lost=
Need to edit "addon.py" in kodi path: "addons/service.iptv.manager/resources/lib/modules/addon.py" 
FIND:
Ligne 254

CHANGE:
def _wait_for_data(self, sock, timeout=10):

TO:
def _wait_for_data(self, sock, timeout=None):

No EPG=

Activate hiden folders/files in kodi:
Kodi > Settings > Media > General > View hiden folders/files.
2. Manualy define location of m3u8 and EPG xml files.
Kodi > Settings > Addons > My addons > PVR Client > IPTV Simple client > Settings > Edit "Migrated Addons"
M3U file: Browse local > "Personal folder > .kodi\userdata\addon_data\service.iptv.manager\playlist.m3u8"
Fichier EPG: Browse local > "Personal folder > .kodi\userdata\addon_data\service.iptv.manager\epg.xml"

**Comment by calvin4242** [comment]
Ok no problem we will solve this 
First make sure "IPTV simple client" has good settings:
Kodi > Settings > Addons > My addons > PVR Client > IPTV Simple client > Settings > Edit "Migrated Addons" > General
Check that Tick the box is "Activated".  This is the place where i asked youy before to enter manualy LOCAL path for epg.xml file.

And
Go to Addond programs > IPTV manager > Settings > IPTV simple 
-configure iptv simple automatically
-Tick "automatically restart IPTV simple.."
IPTV manager > Settings > Channels > refresh channels & guide now

Normally all this before is needed but EPG won't work yet because miss one thing that consist in creating a file :
Go to 
\Userdata\addon_data\pvr.iptvsimple\
You should have 1 file named "settings.xml". If you already have another file "instance-settings-1.xml" everything is ok. Nothing more to do.
If there is no "instance-settings-1.xml" you have to  copy-paste "settings.xml" TO "instance-settings-1.xml". (Keep a copy of "settings.xml" side by side in case of).

**Comment by Jaunattend** [comment]
Wahou thanks a lot !!!! Perfect and clear indication.

**Comment by Jaunattend** [comment]
Thanks 😊

**Comment by calvin4242** [comment]
does it works for you?
