### ISSUE TITLE
Blaze Tv Live & Catchup (UK) Not Working

### ISSUE THREAD

**Issue by snoopymail** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1370]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is: New urls?

### To Reproduce
Steps to reproduce the behaviour:
1.
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:
 - Catch-up TV & More version:
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by nictjir** [comment]
blaze tv have changed things a lot on their site. I can't open the m3u8 file due to geo locking, but i think the attached file should make live tv work - if somebody can test.

Please download
blaze.txt
and rename it to blaze.py and replace your existing blaze.py with this file and test.

[blaze.txt](https://github.com/user-attachments/files/15865287/blaze.txt)

**Comment by snoopymail** [comment]
Live tv works perfectly. Thank you... Would it help if I attach an m3u8 file from the catchup section of the website?

**Comment by nictjir** [comment]
Thank you for testing.  I need to clean up the code a bit and look at
Catchup.  Any links you see for Catchup and the url of the m3u8 will help

**Comment by snoopymail** [comment]
Blaze TV Catchup url: https://watch.blaze.tv/page/catchup/

[Aliens and the Lost Ark](https://watch.blaze.tv/watch/vod/24847725/aliens-and-the-lost-ark)
https://watch.blaze.tv/watch/replay/24847725

playlist.m3u8: 
https://vod.blaze.tv/mediacache/_definst_/smil:s3blaze/110/encoded/135817.smil/playlist.m3u8

[playlist.txt](https://github.com/user-attachments/files/15871943/playlist.txt)

chunklist_b1974272.m3u8: https://vod.blaze.tv/mediacache/_definst_/smil:s3blaze/110/encoded/135817.smil/chunklist_b1974272.m3u8

[chunklist_b1974272.txt](https://github.com/user-attachments/files/15871942/chunklist_b1974272.txt)

**Comment by nictjir** [comment]
Can you try this version please
Still struggling with parsing the html text to give info, ep number, duration etyc of each episode but if you can see if live and catchup work
Still need to optimise repeated code but just what to see I am on the correct track first. Thank you
[blaze.txt](https://github.com/user-attachments/files/15915981/blaze.txt)

Please download
blaze.txt
and rename it to blaze.py and replace your existing blaze.py with this file and test live and replay

**Comment by snoopymail** [comment]
Live TV and Catchup work perfectly now... Many thanks for allk of your hard work! I think it might be a better idea to get the Catchup listings from the following URL as the listing details (titles) are more acurate and updated regularly: https://watch.blaze.tv/catchup

**Comment by nictjir** [comment]
Hello, if i could ask you to please again retest - 1 have cleaned up the code and made series with 1 episode work
[blaze.txt](https://github.com/user-attachments/files/15928071/blaze.txt)

I still cannot work out how to extract the Series/episode number from the nested span, have left a comment in
the list_videos definition - if anybody can help work this out for me please?

Also, if you change your 
plugin.video.catchuptvandmore/resources/lib/skeletons/uk_live.py
to this one
[uk_live.txt](https://github.com/user-attachments/files/15927809/uk_live.txt)

you should hopefully be able to watch a few more live channels from Blaze (art work on list screen is still just blaze logo)  - they are at the bottom of the list. I can't test this due to geo restrictions and not being able to work around it but if you can see if the stations play and its the correct station playing for what is selected

**Comment by snoopymail** [comment]
Live TV and new channels work perfectly. Catchup TV and episode descriptions are also perfect! Thank you so much for this! One thing I have noticed recently,  channel STV doesn't have audio and this also happens when I play the m3u8 through VLC player. STV Catchup is fine though... No idea what the issue is...

**Comment by nictjir** [comment]
Thanx for testing - here is a slightly modified version that shows durations and episode numbers (eventually)
I will submit
[blaze.txt](https://github.com/user-attachments/files/15937020/blaze.txt)
 a mr request in the next few days


For STV not sure thinking maybe one of the formats in the playlist contain a sound encoding your device dose not support - maybe delete the options one at a time and see if vlc will paly the stream from the m3u8 file?

**Comment by joaopa00** [comment]
Fixed in Git. Thanks @nicjir.
