### ISSUE TITLE
Etude - Enregistrement des direct TV

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#144]
Les enregistrements de direct TV sont possibles grâce au plugin IPTV Recorder et PVR IPTV Simple.

- [x] Test OK IPTV Recorder (https://github.com/primaeval/plugin.video.iptv.recorder) et PVR IPTV Simple (répo officiel de Kodi)
- [x] Documentation dans le fichier README_LIVE_TV.md (branche dev)
- [x] TODO test TVHeadend
- [x] Ajout de la documentation sur https://catch-up-tv-and-more.github.io/

**Comment by wwark** [comment]
Done !

**Comment by thombet** [comment]
Hello @wwark, I dig up an old issue but it is the only one mentioning tvheadend :)
I would like to watch live TV using this add-on but with tvheadend (not IPTV simple client). Did you manage to make it work with tvheadend?

On my side I tried to import the m3u and it resulted in this error:
```
iptv: unknown playlist format for network '<network_name>'
```
Then I tried to manually set the MUX with the `plugin://` URL but it failed again with the following error:
```
iptv: <channel_name> in <network_name> - unsupported scheme [none]
```

I'm not sure the problem comes from this add-on or tvheadend so I thought I would ask you first if you managed  to make it work before creating an issue here or on tvheadend's forums.
Thanks!

**Comment by wwark** [comment]
Hi @thombet,

Sorry, I don't make the test on tvheadend.

The format used on our m3u files is not part of the m3u specification... and regarding your issue, tvheadend doesn't seem to like them ....

The format of the m3u8 file is to call some part of the code of the plugin to play the content like if you are on the plugin but in IPTV Simple client. 

@SylvainCecchetto I think we can't help for this case. Do you have another idea ?

Thanks,

**Comment by SylvainCecchetto** [comment]
Hi,

I personally use TVHeadend on my daily usage with my local network TNT tunner.
I never tried to give our M3U to TVheadend, I will try 😉

**Comment by thombet** [comment]
Thanks both of you!

I looked up a bit more how to make this working and I think the `pipe://` feature of tvheadend is probably the only thing that could work: https://tvheadend.org/projects/tvheadend/wiki/Custom_MPEG-TS_Input

For instance it seems it can be used to play YouTube videos as explained [here](https://tvheadend.org/issues/3881). I think the problem is that the tvheadend back-end must be able to execute the part after `pipe://` which is not really the case with `plugin://`like URL...

A couple more examples that could be:
- [Using livestreamer](https://tvheadend.org/boards/5/topics/15853?r=24095)
- [Another example with ffmpeg](https://tvheadend.org/boards/4/topics/27112?r=27119#message-27119)

**Comment by SylvainCecchetto** [comment]
You seems to be on the right track!!

I tested on my local Tvheadend, but like you it does not want to add the M3U entries as services.
It would be nice to find a way to "force" Tvheadend to add each URL entry of the M3U file without testing it.
But even with this setting, I am pretty sure that when Kodi open the "channel", Tvheadend will try to stream the video flux from the URL entry to Kodi...

It doesn't cost anything to ask perexg, I will try to open an issue to ask him.

**Comment by Forage** [comment]
I was just pondering about the same thing, but I think live TV from Kodi through Tvheadend is a dead end.

The tvh server has no knowledge of kodi, nor should it, so it won't understand internal kodi references to address a specific plugin.
It would only work if kodi had some external api which provides a direct stream based on some form of url called externally. These could then be included in an m3u file for tvh to digest.
