### ISSUE TITLE
Multiple channels not working

### ISSUE THREAD

**Issue by flof08** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#180]
Since quite a while (1-2 months), I am unable to receive France 2 (also France 3, 4, 5), and RMC Decouverte.
I am a little bit surprised to see no mention of such an issue here?

I tried everything, de-install / re-install Catch-Up TV, tried a different version (Beta)
Re-install Kodi clean

Nothing seems to solve the issue.
Any idea?

Note:
It may be a VPN issue, but if I connect my VPN on my computer and access France TV live from it, it works, so it does not seem to be related to the VPN issue.
RMC decouverte issue seems to be related to something different.

Here is the link to the Kodi log:

https://pastebin.com/Cr8ZL5j6

Setup:

12:30:55.928 T:1944975824  NOTICE: Starting Kodi (17.6 Git:a9a7a20). Platform: Linux ARM 32-bit
12:30:55.929 T:1944975824  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
12:30:55.929 T:1944975824  NOTICE: Kodi compiled Apr 13 2018 by GCC 6.2.0 for Linux ARM 32-bit version 4.9.80 (264528)
12:30:55.929 T:1944975824  NOTICE: Running on LibreELEC (official): 8.2.5, kernel: Linux ARM 32-bit version 4.9.80
12:30:55.929 T:1944975824  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
12:30:55.929 T:1944975824  NOTICE: Host CPU: ARMv7 Processor rev 4 (v7l), 4 cores available
12:30:55.929 T:1944975824  NOTICE: ARM Features: Neon enabled

Many thanks in advance!
Florian

**Comment by wwark** [comment]
Hi @flof08,

You have a lot of logs and a lot of cases.
First of all your version of the plugin is 0.2.6 (last release) can you please confirm it?
I confirm to you the France TV lives tv work without issue from France.
Most of the contents are geo-blocked and using a VPN cannot solve the problem. The using of a VPN can be detected.

I saw some tests regarding France TV. The error are HTTP 403 "not authorized". In this case did you use your VPN? 
I saw also timeout it means the timeout of Kodi is raised maybe because a slow connection (for that you have some options here : https://kodi.wiki/view/Advancedsettings.xml#network)

Is it possible to produce two more tests with debug log of kodi activated?
* Live TV France TV
* Live TV RMC Decouverte

Thanks,
Wwark

**Comment by flof08** [comment]
Hi @wwark ,

I realise now that I forgot to answer you.
I was able to solve the issue by myself.
Posting here what I did, in the case it helps someone in the same situation:

- Rejuvenate Kodi with Indigo Add-on
- Clear Catch up TV & More Cache from the add-on settings (available in "advance").

Closing the issue, since solved for me.

Florian
