### ISSUE TITLE
Python exception "coercing to Unicode: need string or buffer, NoneType found"

### ISSUE THREAD

**Issue by xam60** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#195]
Bonjour,

J'utilise Catch-up-TV-and-More avec l'addon Embuary https://github.com/sualfred/skin.embuary/

A chaque démarrage de Kodi, j'obtiens une erreur "coercing to Unicode: need string or buffer, NoneType found".

C'est lié à la dépendance script.module.unidecode de l'addon script.skinshortcuts utilisé par Embuary.

Voici un log de debug :
https://paste.kodi.tv/igetoliwec.kodi

Plateforme sur laquelle le problème se produit : Android TV (Nvidia Shield & Xiaomi Mi Box)

Merci d'avance

**Comment by wwark** [comment]
Bonjour @xam60,

Est-ce qu'il serait possible de supprimer le répertoire ".kodi/userdata/addon_data/plugin.video.catchuptvandmore"
Ce répertoire contient tous les fichiers utilisateurs de CU TV&More. Ce point permet de faire une remise à zéro.
Merci,
Wwark.

**Comment by xam60** [comment]
Bonjour @wwark 

Il n'y a pas d'amélioration, le message d'erreur apparaît toujours lors du démarrage de Kodi : 
https://paste.kodi.tv/raw/cagalopoju

Merci
xam60

**Comment by xam60** [comment]
Bonjour !
Après avoir cherché plus en détail, je me suis rendu compte que le problème venait des raccourcis de l'addon Embuary. J'avais créé deux raccourcis vers CU TV&More qui ne se rafraîchissaient plus : en les supprimant et les recréant, l'erreur n'apparaît plus.

Merci et désolé du problème
xam60

**Comment by wwark** [comment]
Bonjour, cool ! Il faudrait prévenir le mainteneur de embuary. Le problème peut se reproduire. Merci Wwark

**Comment by sualfred** [comment]
@wwark 
I'm the dev of Embuary. Can you please let me know what exactly is causing this issue? I'm not familiar with your addon or how it works. And I don't know any FR.

**Comment by wwark** [comment]
Hi @sualfred, 
This add-on use the framework codequick and we proposed some catch-up TV and live tv from different country.

If I understand correctly the messages from @xam60, he created some shortlink in Embuary and those shortlinks have some issue in Embuary.
My guess is the link didn't work anymore because the link point to nothing (website remove content) or we changed the code of the catch-up TV website because of the server changes.

@xam60 recreate those shortlinks and it is working again in Embuary.

I hope it might help. Do not hesitate if you need more informations

Wwark

**Comment by sualfred** [comment]
Ok, so it is/was mostly an issue with the configured shortcut of the script.skinshortcuts script.
