### ISSUE TITLE
Selecting lower quality steams

### ISSUE THREAD

**Issue by oluc** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#265]
Hello,

I'm trying to setup Kodi to watch TV over a slow connection. Default streams are too heavy for the connection. I'd like to access lower quality streams. I set "DIALOG" as video quality, but some channels does not show any dialog.

As a specific example, France TV (live and replay) does not show quality dialog, despite it has several stream quality.

It looks like a missing part, how could we make this happen ?
(or did I miss something in my config?)

Example from France.TV, multiple stream quality,

**## Live TV**
```
$ youtube-dl -F https://www.france.tv/france-5/direct.html
[info] Available formats for 45007886-f3ff-4b3e-9706-1ef1014c5a60:
format code                          extension  resolution note
hls-audio-aacl-98-Audio_Description  mp4        audio only [qad] 
hls-audio-aacl-98-Francais           mp4        audio only [fra] 
hls-audio-aacl-98-Version_Originale  mp4        audio only [qaa] 
hls-235                              mp4        256x144     235k , avc1.42C01E, 25.0fps, video only
hls-534                              mp4        384x216     534k , avc1.42C01E, 25.0fps, video only
hls-1117                             mp4        640x360    1117k , avc1.42C01E, 25.0fps, video only
hls-1594                             mp4        960x540    1594k , avc1.4D401F, 25.0fps, video only
hls-2866                             mp4        1280x720   2866k , avc1.4D401F, 25.0fps, video only (best)
```

**## Catchup TV**
```
$ youtube-dl -F https://www.france.tv/france-5/histoires-de-chats/saison-1/429087-incroyables-felins.html
[info] Available formats for df92f63a-3312-44be-86a9-9044c9d6b787:
format code                             extension  resolution note
hls_v5_os-audio-aacl-64-Audio_Français  mp4        audio only [fr] 
hls_v5_os-191                           mp4        384x216     191k , avc1.42C01E, 25.0fps, video only
hls_v5_os-321                           mp4        640x360     321k , avc1.4D401F, 25.0fps, video only
hls_v5_os-609                           mp4        960x540     609k , avc1.4D401F, 25.0fps, video only
hls_v5_os-880                           mp4        1280x720    880k , avc1.64001F, 25.0fps, video only (best)
```

**Comment by wwark** [comment]
Hi @oluc,

In the player Kodi (during video played) (18 and above) you can select program (bitrate = quality) if the content provided it.
Is it can answer what you ask ?

Regards,
Wwark

**Comment by oluc** [comment]
Hi @wwark 
thanks for the reply! I overlooked this menu, it technically works, though from UX point of view, that's about 15 clicks for each video, pretty much unusable for daily use (and for my 80yo aunt). I am wondering how is the setting BEST|DEFAULT|DIALOG different? Is there a way to set the quality once for all?


(feel free to close the issue of it becomes irrelevant here)

**Comment by SylvainCecchetto** [comment]
Hi oluc,

Our `BEST|DEFAULT|DIALOG` setting and the built-in `select program` Kodi setting are two different things:

As you should know, in our add-on, we use Python to grab video contents from official catch-up TV provider websites.
Sometimes, for a video, we are able to get multiple URL with different quality/format, in this case we use the `BEST|DEFAULT|DIALOG` setting in order to give the user the choice of the quality.

The other case is when we grab a `m3u8` file. In this case our `BEST|DEFAULT|DIALOG` setting does nothing and we directly give this file too Kodi player.
These types of files contain multiple quality so the video player can select and adjust the quality to use depending on your network bandwidth. 
So Kodi will select the best quality depending on your network. Also you can manually select the bitrate that you want with the `select program` Kodi setting.

I hope I haven't said too much stupidity, @wwark may correct me.

**Comment by oluc** [comment]
Hi, thank you very much for the detailed comment !
I managed to get a better connection, so I don't have this difficulty anymore.
