### ISSUE TITLE
RTBF Auvio replay Season content not available

### ISSUE THREAD

**Issue by doczico** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#295]
Hello,
Auvio provide full seasons for many series but only the first episode is available trough catch-up
### To Reproduce
1. Catch-up TV -> Belgium -> RTBF Auvio -> Series ->
2. Nos Series Belges OR Series Corner
3. Only the first episode of each series is available while the full season is available via the website (example with la treve)

### Expected behavior
Full content available and may be categorized by series

### Actuel behavior
Only Ep01 is available and all series at the same level
### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: coreelec
 - Kodi version: 
 - Catch-up TV & More version: 0.2.21~beta2
 - Installation method: official repo 

Thank you Very much in advance for your help / fix and HUGE thank you for the work already done ! It is awesome 

Best Regards
Federico

**Comment by wwark** [comment]
Hi,
Thank you for the report.
I saw on the website there is juste one episode proposed in this page like the screenshot.
![Screenshot from 2020-04-27 17-24-09](https://user-images.githubusercontent.com/469461/80390053-3600dc80-88ac-11ea-8bb4-8e60338c9f35.png)

I understand if you select on of the episode more episodes is propose in another page but the plugin cannot work like that because the website propose two views for the same click not applicable on the plugin.

However, you could find all episodes of a serie on the menu "All programs".

Hope my response will help !
Regards,

**Comment by doczico** [comment]
Hello,
Thank you for the quick response
unfortunately the program i'm looking for is missing from "all programs"
(la treve).
I checked on auvio website and it is also missing from the 'emission'
category.
As it looks like an error from auvio i sent them an email asking to add
that series in all programs aka emission

Best regards
Federico

**Comment by wwark** [comment]
Thank you for your return.
Yes there is some errors in the website.
I closed this ticket.
Do not hesitate if you need to reopen it.

Thanks,
Wwark
