### ISSUE TITLE
STV Catch-up incomplete 

### ISSUE THREAD

**Issue by chrissxuk** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#512]
### Describe the bug
A clear and concise description of what the bug is: 
When looking in the catch-up UK STV folder the shows are not complete. There are no shows after "S".

### To Reproduce
1. Open Catch-up TV Folder 
2. Open United Kingdom Folder 
3. Open STV Folder

### Expected behavior
A clear and concise description of what you expected to happen:
All available Catch-up shows should be listed from A to Z

### Actuel behavior
Tell us what happens instead:
277 Shows are listed and stop at "S"

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: Formuler Z8 and Firestick Lite
 - Kodi version: 18.9 and 19
 - Catch-up TV & More version: 0.2.34
 - Installation method: Kodi Repository 

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by sy6sy2** [comment]
Hi @chrissxuk,
Is it possible for you to install 0.2.36~beta02 version of the plugin and check if your issue is fixed?

You can install it manually with zip file or you can use our beta channel repo to automatically get any new beta version of the plugin (see https://catch-up-tv-and-more.github.io/installation/#ii-add-the-official-catch-up-tv--more-repository)

**Comment by chrissxuk** [comment]
With the new category listings this appears to have fixed the problem. Thank you very much.

**Comment by sy6sy2** [comment]
Perfect!
