### ISSUE TITLE
No EPG on La Trois (B) 

### ISSUE THREAD

**Issue by Rvhalewyn** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#577]
### Describe the bug
A clear and concise description of what the bug is: No EPG on La Trois (B) 

### To Reproduce
1. Open EPG grid, works with IPTV Manager 
2.Other channels have EPG, not La Trois Belgique 
3.
4.

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 
 - [ ] Other: Libreelec 

 - Operating system version/name: 9.2 5
 - Kodi version: 18.9
 - Catch-up TV & More version:0.2.36
 - Installation method:

**Comment by sy6sy2** [comment]
Hi,
ATM I have a program for La Trois (see my screenshot).
Because I use a French EPG TV grabber, I guess that sometimes some programs are missing for Belgian channels... sorry about that.
If someone want to help/improve the EPG part of the plugin, feel free to open a PR on https://github.com/Catch-up-TV-and-More/xmltv 😉
