### ISSUE TITLE
Ajouter une option pour désactiver les extraits

### ISSUE THREAD

**Issue by funtravel1208** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#62]
Bonjour,

Je viens de constater qu'il y a beaucoup de replays de chaines francaises qui affichent des replays de pas plus de 1-2 min, et meme des replays affichant la durée correcte de l'émission mais qui ne durent que 2 min...
Exemples d'émissions: France 2 - Les pouvoirs extraordinaires du corps humain; Infrarouge et plein d'autres documentaires... Y a t'il un problème???
Merci d'avance pour votre aide...

**Comment by wwark** [comment]
Hello,
Le plugin récupère les informations proposés sur le site du replay.
Sur les replays France 2 nous avons des extraits et des émissions complètes.
La durée n'est pas correcte dans tous les cas pour France TV. Nous allons regarder ce qui possible de faire sur la durée.
Merci,
Wwark

**Comment by wwark** [comment]
Hello,
Je viens de commiter sur la branche de développement.
L'ajout de l'information si c'est un extrait ou non et supprimer la durée pour les extraits.

J'espère que ce changement permettra de repondre au point remonté dans ce ticket.
Merci,
Wwark

**Comment by funtravel1208** [comment]
Bonjour,

OK c’est une bonne idée. Je pense que les extraits n’apparaissaient pas avant. Pourriez-vous ajouter un dossier séparé pour les extraits? Personnellement je ne suis pas intéressée par les extraits et souhaiterait avoir accès facilement et directement aux émissions.

Merci beaucoup!!!!

Christine

**Comment by wwark** [comment]
Bonjour,
Oui c'est la nouvelle API de France TV (l'autre ne permettaient plus de mettre à jour les émisions)
J'ai changé le titre et propose d'ajouter une option dans le plugin pour activer ou non les extrais.

Nous regardons ce point et fermerons le ticket quand ce sera implémenter dans le plugin.

Merci,
Wwark

**Comment by funtravel1208** [comment]
Bonjour Marc,

Je viens de tomber sur un nouveau problème de Catch Up TV. Tous les journaux télévisés de 2018 ont disparu... 
Merci de voir quel est le problème!

Christine

**Comment by wwark** [comment]
Bonjour Christine,

Sur le site de France.TV, ils semblent avoir des soucis https://www.france.tv/france-2/roland-garros/ Les vidéos datent de juin 2017.
Certains menu n'existent plus dont les lives.
Ils ont surement eu un problème. On va voir pour que ça se stabilisent. Les replays pour les JT semblent ok par exemple  (JT 20h30 dimanche 27 Mai)
Je regarderai demain soir.

Bonne soirée,

**Comment by funtravel1208** [comment]
Ok, merci pour ces infos!!!! En effet, ils doivent avoir des soucis techniques en ce moment!
En tout cas, merci beaucoup pour cette app!!! Je suis une fan! :)

Christine

**Comment by wwark** [comment]
Merci c'est top d'avoir des fans :) On va pouvoir produire des teeshirts ^^
Sinon je pense que la majeur partie de la partie FranceTV fonctionnent correctement.
Je checkerai  ce weekend pour vérifier si on a encore des soucis.

**Comment by funtravel1208** [comment]
Bonjour Marc,

Depuis ce matin, je n’ai plus accès au Live des chaînes françaises. J’ai un message d’erreur pour le Live France “UnknownTimeZoneError: cannot find any time zone configuration”

Merci de voir si vous pouvez faire quelquechose pour régler ce problème.

Bien cordialement,

Christine

**Comment by Forage** [comment]
Pourquoi inclure les extraits de toute façon ? Nous avons le moyen de les détecter, à mon avis ça sert à rien de les monter. Est-ce que quelqu'un est vraiment intéresser de les voire ?

**Comment by wwark** [comment]
Hello @Forage,

Dans l'API utilisé on remonte les replays et les extraits dans le même appel.
Sur France TV ont a beaucoup d'extrait et certains programmes peuvent avoir les replay dans la deuxième page et que des extrais sur la première page. Si on masque les extraits l'utilisateurs pensera qu'il n'y a pas de replay et n'ira surement pas voir la deuxième page ....
Il faudrait qu'on puisse trouver un appel pour remonter que les replays ...

La façon mytf1 est mieux organisé je trouve mais dépend du site .......

De plus sur FranceTV ils gardent aussi des vieux replays qui ne sont plus lisibles ... mais remonté par l'appel...

Il faudrait creuser un peu plus l'API pour voir si on pourrait limiter les éléments remontés sans perdre de contenus ...

Merci,
wwark

**Comment by Psychoses** [comment]
https://github.com/Psychoses/plugin.video.catchuptvandmore/commit/0c26e06aad62d2f974f86053d327119d72759440

Bonjour wwark, tu en pense quoi ? c'est pushable en l'état ?

**Comment by wwark** [comment]
Bonjour @Psychoses,
Merci !
Il faudrait faire un test de ce code avec RPI2 ou RPI3b+ pour voir si ce changement n'a pas impact trop important sur le temps de chargement.
Ton test est fait sur quel environnement, quel est l'impact sur ton environnement ?

Encore Merci,
Wwark

**Comment by Psychoses** [comment]
Je n'ai pas de rpi à ma dispo.

J'ai push la modif dans mon environnment sur windows, mibox3ab et tv tcl (armv7) et snapdragon625 (aarch64) depuis quelques semaines.

Difficile à dire, je n'utilise pas assez la fonctionalité et j'ai beaucoup d'autres addons gourmands, je pense pas que ca impacte bcp les perfs mais je peux me tromper. J'ai rien remarquer pour le moment.

delai entre clic et affichage du contenu (envoyespecial, cashinvestigation, fortboyard, etc...) :
mido snapdragon625 : 3s
mibox3ab tvtcl (S905 A53/MT5891) : 5s
sur windows (core2duo) : quasi instantannée

**Comment by wwark** [comment]
@Psychoses, j'ai réfléchis.
On pourrait ajouter deux contextes menus (dans liste cf capture d'écran) pour lister les extraits (only-extrait) et les videos de types episode (ton code adapté pour récupérer que les vidéos de type episodes) et mettre les vidéos de type Integral par défaut (only-replay).
![Screenshot from 2019-09-13 19-31-57](https://user-images.githubusercontent.com/469461/64882355-391cc480-d65d-11e9-87d8-3b909ea16e4d.png)

Qu'est ce que tu penses ?

**Comment by wwark** [comment]
Proposition:
![Screenshot from 2019-09-13 20-14-53](https://user-images.githubusercontent.com/469461/64885040-5f456300-d663-11e9-9eac-cee8440d2e3e.png)
![Screenshot from 2019-09-13 20-15-08](https://user-images.githubusercontent.com/469461/64885055-640a1700-d663-11e9-886a-c1c191a2280d.png)
![Screenshot from 2019-09-13 20-15-24](https://user-images.githubusercontent.com/469461/64885074-6ff5d900-d663-11e9-833c-a5912f810ff9.png)
![Screenshot from 2019-09-13 20-15-39](https://user-images.githubusercontent.com/469461/64885086-77b57d80-d663-11e9-8a06-994faa50373a.png)

**Comment by wwark** [comment]
Commité e2a34c1129e69e41bb596f32902299e1c616e4b4

**Comment by Forage** [comment]
Great that you found ways to filter out the nonsense!

What is the difference between "episode" and "integrale" though? This might need a better translation to English (like "extrait" for that matter).

I must say that the way to filter it now is not very intuitive. People won't find it by accident and are likely to asks questions about not getting to see all types of videos now (not that anymore would miss the extraits though). I suppose there still isn't a way to add the filters to the left hand menu that slides out in the episodes list?

Note that if a show does not have a certain type, like episides, but you use this filter anyway, you get an error.

Also, if you stick to the current way of filtering, maybe display the options in a less technical way. Simply "List extrait videos" and "List episode videos" for example.

I don't know if the following is related to the changes you've been making for this issue, but at TF1 I now get "Exclu", "Replay" and "Extrait" sub-list items. Or at least I've never noticed it before. The same error occurs here when certain types don't exist and you try to use that list item.

**Comment by wwark** [comment]
Thank you for your propositions (it is just a first draft need some work like you point !)

For the moment the video with the type episode it seems to be very old catch-up's tv and I found them just for cash Investigation for the moment  (very rare). So I think it is previous type for catch-up TV.
In the case of video type of episode most of the time you will have the notification "No Items Found".

TF1 propose already to class contents so we follow that (France TV it is not the case). It is better to follow how the channel propose contents because it means less code so less issue.

We can also change France TV to follow TF1 with two choice "Extrait" and "Replay" and let episode in context menu just to keep content from cash investigation and maybe remove the context when no more video type episode is available.

**Comment by Psychoses** [comment]
fuck ! why are u speak english this time ? ^^
so let me try in english for fun...

part one about ftv :

1
i think context menu usage are bad here. because how can i add for sample "cash investigation episode list" on my fav ?
![shorcut-prob](https://user-images.githubusercontent.com/11153449/64908529-ba2d9780-d701-11e9-8b6b-623ed720c6c3.png)

2
there is more. not just episode (like you, i have only see that on "cash investigation"), integrale, extract.
i have spot other stuff.
i have use that :
```
    # What about "teaser" and "resume"?
    # E.g. http://api-front.yatta.francetv.fr/standard/publish/taxonomies/france-3_plus-belle-la-vie/contents/?size=20&page=0&sort=begin_date:desc&filter=with-no-vod,only-visible
    if video['type'] == "extrait":
        item.label += "[" + video['type'] + "] "
    elif video['type']:
        item.label += "[" + video['type'] + "] "
    else:
        item.label += "[No Type] "
```

and i have spotted "film" or "bande-annonce" categories on "doc/Infrarouge" and many "[No Type] "
![infrarouge](https://user-images.githubusercontent.com/11153449/64908553-27412d00-d702-11e9-9397-71c300adc829.png)
![cash](https://user-images.githubusercontent.com/11153449/64908554-2a3c1d80-d702-11e9-963b-31d17124299a.png)


3
we cant delete extract for item with only extract like "societe\dans les yeux d'olivier". content is only extract.

a good approch will be :

for france tv, do like tf1, we copy how tf1 works :

on tf1 with have a step where py presume cat :
```
VIDEO_TYPES = {
    'Replay': 'replay',
    'Extrait': 'extract',
    'Exclu': 'bonus'
}
```

on ftv we can presume 3 cat :
-"all vids cat" (with all content extract or not) (can be used for slow devices) => use standart function
-"extract" => use only_extract api
-"Other ?" (with all content without extract) ==> use 5000 way (never use only_replay for dont lost "film", "episode", "bande-annonce" or "No Type")

with that approch :
- we dont lost any vids on "cash investigation" or "infrarouge"
- slow device like rpi can always use first item and so execute the standard 20item function
- no more problem with "societe\dans les yeux d'olivier" => extract cat works
- user can add wanted stuff on fav

=================================

part two about empty subcat :

But if we go on that, the tf1 problem with empty item will appear to on ftv.

> I don't know if the following is related to the changes you've been making for this issue, but at TF1 I now get "Exclu", "Replay" and "Extrait" sub-list items. Or at least I've never noticed it before. The same error occurs here when certain types don't exist and you try to use that list item.

We can maybe add a main settings addon like "i don't use a slow device and i want try to skip empty item if possible":

if slow device show empty cat : for sample  "tf1\seriesfiction\4400\exclu" => "show error item found" like current version

if new settings used : use 5000 way => build item "Exclu\Replay\Extrait" only if 1 videos with this type is found. if only 1 subcat is found go directly on it.
for sample : "tf1\seriesfiction\4400" => 5000 way => py files found only replay vid => so we can display directly all replay item.
![4400](https://user-images.githubusercontent.com/11153449/64908772-75573000-d704-11e9-9a7e-400801b1f522.png)

i use already this approch on a custom version of mytf1.py

![if-fast-device](https://user-images.githubusercontent.com/11153449/64908791-9d469380-d704-11e9-9bdb-5c6557b4ff6b.png)

I would like to have your opinion now ^^

**Comment by wwark** [comment]
Thank you for all your comment.
I pushed something taking in account some part your proposes.
I put 500 (other videos) because just get around 150 videos take some times on high end device so it can be painfull in RPI (example Dans quelle etagères actualité France2) and I prefer not pull to many the TF1 channel and France TV because we might be blacklisted. 

I prefer to let all videos category to limit the code. (so less issue :))

Thanks again for your help and propositions.
I closed this long standing ticket !
