### ISSUE TITLE
Additional replay episode details

### ISSUE THREAD

**Issue by Forage** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#84]
For the lack of a different way to contact you directly, I've got a couple of questions before I look further in adding some channels and/or improve existing ones.

1. At the moment I don't really see it being done, but would it be acceptable to call a separate webpage per replay episode to extend the details of the episode, like plot, image, etc.? It comes at the cost of increased load duration, but these details are not always to be found on one overview page. Besides not having this info makes it look incomplete, it is also practical/interesting to have.
2. What is the difference between the `date` and `aired` timestamp in the episode details and why does it have a different format? (year-month-day vs. day.month.year)
3. Navigation though the pages can be quite slow. I have the impression it tries to load a lot, if not all, of the content of all subpages (like all series under a channel in the list of channels for a specific country) as well. If this is the case, would it be an option to make this behaviour optional?

**Comment by wwark** [comment]
Hi Forage,

It will be great to have you to help us (sy6sy2 and me) :) 

1- Yes this part we do the minimal sometimes just the title and the picture because for two points (if the website change it will create issue and it will take times to show on the plugin)
If we call separate page for all replay (exp +100 pages) we download 100 times pages and scrappe them. this part takes times.
Sy6sy2 is working to change the framework "codequick" maybe we will have some gains on rapidity. We will need to migrate all channels so your help can be good and maybe improve the informations for each replay.
2- aired and date are properties of the video. For that we are not very good at it also ... some documentation of kodi explained original aired for TV Show and it is used to have a order by aired date of the tv show. (https://kodi.wiki/view/Naming_video_files/TV_shows)
In Replay it might be difficult but most of the time we set the same value for aired and date.
3- With the work with codequick and the refactoring to use this new framework we will work to minimise the load needed. Sy6sy found we make to many calls between some modules. the framework Codequick propose also to keep session by default it will help to simplify some part of the code.

Thanks,

**Comment by Forage** [comment]
Thank you for your reply wwark.

It will remain a call to a lot of separate web pages, even if you do manage to speed up the overall add-on performance. So maybe it should be an option, allowing users to choose speed over details. It will depend on the channel if the details are available on an overview page, on separate pages or not at all.

While there might be a reason between the different dates, the two having a different format is what strikes me as a bit odd. Maybe just for legacy reasons, but I don't think localisation should be done on database level.

Let me know when the codequick branch is in a state where one or two channels have been adapted to the new way of including them. I would be mostly interested in adding a few missing channels from that point, but we'll see how things will work out.

**Comment by SylvainCecchetto** [comment]
Hi Forage,

Delighted that you are interested in this project ;-)

First I will try to complete the wwark's answers to your questions:

1- Yes I am agree with you: it would be nice if we had more informations for each element (season, categories, episodes). But as you say we sometime need to scrap differents pages one by one and it can take a lot of time...
I am agree with the "setting" that let the user to enable or not the "More informations but less speed" option. Of course we have to speak about that together ;-)

2- concerning the `date` and `aired` properties I was a bit lost too at the beginning. But yes, I think it's something like `first date` and `last date on the TV` but I'm not sure.
Concerning the different format of `date` and `aired`, codequick fix this "issue" with a simple `date` function that change the format for us and automatically add the `date` and `aired` properties to the item in one time (see 
https://scriptmodulecodequick.readthedocs.io/en/latest/_modules/codequick/listing.html#Info.date)

Like Wwark said, I am currently working on an alpha version of the plugin with the new framework (CodeQuick), the goal is multiple:

* Leave SimplePlugin framework because it is no more maintained
* Be ready to have the plugin 100% working with Python 3 (Because Kodi team want to switch to Python 3)
* CodeQuick was specially designed to the Kodi add-ons scrapper like Catch-Up TV & More
* CodeQuick come with a simple API, Youtube-DL, a Web-scrapper with embedded downloader
* The goal is to have only one dependency : Simpleplugin and remove one by one "BeautifulSoup", "Request", etc ...

In the same time I will try to create a separate project to "test" our plugin.
The desired features of this project:

* Be able to try our channel python file without Kodi (the scrapping part) directly with the terminal. The script will "build" the menus and item in the same way as Kodi would. I think that it's easier and faster to debug the scrapping part without Kodi and directly with terminal.
* Be able to completely test a channel python file by automatically enter in each menu of the channel (a deep course of the channel). And catch any error. At the end the script will be able to list the submenus or video that don't work.
Because they are more and more channels and it takes time to try each channel one by one...
Maybe in the future we will able to create a Travis integration?

So to finish, I am currently working on the "codequick" branch of the repo to try the new framework. I think that in a few days this version will works with one or two channels and you will can check that ;-)

Oh and we also have in our TODO list the Wiki pages to do... But the time is not always with us.. I hope that with the new version of the add-on with the new framework we will be able to write it in order to make easier the development of new channels of other developers.

See you soon ;-)

**Comment by Forage** [comment]
Great, thanks for the heads-up :)

Did it already deliver the speed improvement, in terms of navigating, you were hoping for?
If not, would caching be an option to at least reduce loading when visiting the same screen for a second time in a short period?

I'll try to take the dev sources for a spin, though I'm not sure if simply replacing the current sources in the add-on folder will suffice.

**Comment by wwark** [comment]
Also, a new version of codequick will be released with some tunings and some bug fixes.

**Comment by wwark** [comment]
I closed this ticket.
If needed we can open a new one for a specific case.

Thanks,
Wwark
