### ISSUE TITLE
Country and channel icons no longer shown in list

### ISSUE THREAD

**Issue by Forage** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#94]
Just a quick note, instead of throwing everything in the other issue (#84).
In the codequick dev version, country and channel icons are no longer shown in list. Only in big on the side when selected.
Instead, all entries have a default folder icon. Is this by design or a todo? I tend to find it helpful to have when navigating and it renders navigation a bit less 'technical' going through multiple lists that all look the same otherwise.

**Comment by SylvainCecchetto** [comment]
Hi Forage,

Yes we notice that too, this is not really an issue because we can restore the old behavior by setting the `item.art['icon']` property in addition to `item.art['thumb']` (I think).
If I'm not wrong, the first one (icon) sets the image for the item in the listing and the second one (thumb) sets the image for the "side panel".

What do you think about that @wwark ?

Thank you Forage for the question ;-)

**Comment by wwark** [comment]
Ok to set it also ! :+1:

**Comment by Forage** [comment]
Great, thanks :)

**Comment by wwark** [comment]
Ticket opened by @SylvainCecchetto after some tests https://github.com/willforde/script.module.codequick/issues/20

**Comment by SylvainCecchetto** [comment]
Hi @Forage,
This is an old issue, but as willford said : 

>  [...] the only way to get Kodi to work the way you want (icons in list), is to not set any content_type at all. The "videos" content type is what is recommended by Kodi. [...]

After some tests, it seems that set `content_type` to `None` disable a lot of "view mode" for the current list.

So we think that it's better to keep the `videos content_type` despite the absence of icons.

Is it ok for you?

**Comment by SylvainCecchetto** [comment]
I (temporary) close this issue, if needed we can reopen it ;-)
